apiVersion: v1
kind: Service
metadata:
  name: tickets-db
  labels:
    operator: ticket
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    app: tickets-db  
  clusterIP: None