version: '3'

services:
  tickets-db:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=anaskhafaga
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    volumes:
      - data:/data/db
    networks:
      - tickets
  tickets-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "4000:3000"
volumes:
  data:

networks:
  tickets:
