apiVersion: v1
kind: Service
metadata:
  name: tickets-proxy
  labels:
    operator: ticket
spec:
  ports:
    - port: 5000
      targetPort: 80
  selector:
    app: tickets-proxy
  type: LoadBalancer