apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-web
  labels:
    operator: ticket
spec:
  selector:
    matchLabels:
      app: tickets-web
  template:
    metadata:
      labels:
        app: tickets-web
    spec:
      containers:
        - name: web
          image: tickets-app
          imagePullPolicy: Never
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: tickets-web-secret
                  key: MONGODB_URI
            - name: NEXT_PUBLIC_DATA_ENDPOINT
              value: tickets
